# Generated by Django 6.0 on 2025-12-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naziv kluba', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Skraceno ime', null=True, unique=True)),
                ('country', models.CharField(help_text='Drzava kluba', max_length=150)),
                ('city', models.CharField(help_text='grad kluba', max_length=150)),
                ('league', models.CharField(help_text='liga kluba', max_length=150)),
                ('founding_year', models.PositiveIntegerField(blank=True, help_text='Godina osnutka kluba', null=True)),
                ('stadium', models.CharField(blank=True, help_text='Ime stadiona', max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, help_text='Url za sliku grba', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ime igraca', max_length=50)),
                ('birth_date', models.DateField(help_text='Datum rodjenja')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], help_text='Pozicija igraca', max_length=2)),
                ('picture_url', models.URLField(blank=True, help_text='Url za sliku igraca', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='football.club')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['name'],
            },
        ),
    ]
